# from: https://github.com/marketplace/actions/markdown-linting-action

name: Validate pattern syntax

on: [push, pull_request]
jobs:
  validate-pattern-syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint pattern files (markdown)
      uses: avto-dev/markdown-lint@v1
      with:
        rules: './lint/pattern-template.js'
        config: './lint/pattern-template.yml'
        args: '-i README.md -i TRUSTED-COMMITTERS.md -i CONTRIBUTING.md *.md'
